### ISSUE TITLE
multiple problems with jsreport embedded server Node.exe [2]

### ISSUE THREAD

**Issue by paulodiogo** [jsreport/net#13]
I'm getting many issues when the IIS server has more than one app that uses the embedded server.

The server stops after the restart of the pool;
The node.exe freeze and the process do not answer more;
The node.exe begins consume a lot of memory (like 1.5gb) then it's killed;

In other words, it seems like that there is a problem with the node.exe and jsreport.

**Comment by pofider** [comment]
You run the embedded server on different ports on each app, right?

**Comment by paulodiogo** [comment]
@pofider yes, each one has one port...

**Comment by pofider** [comment]
Ok,

jsreport.embedded tries to restart all the running node process when you call `StartAsync`. And I guess this is called after the app pool is started.

https://github.com/jsreport/net/blob/master/jsreport/jsreport.Embedded/EmbeddedReportingServer.cs#L142

The [AssemblyDirectory](https://github.com/jsreport/net/blob/master/jsreport/jsreport.Embedded/EmbeddedReportingServer.cs#L144) path is used to determine the node process which belongs to particular web app inside iis. It looks to me it should kill the right process and start it again.

I'm too busy to fiddle with the multiple web apps in the iis at this moment. Maybe you can git clone the jsreport.embedded project, reference it in your app and find out more info?

**Comment by paulodiogo** [comment]
@pofider I think that the problem is the node.exe blocked but something else, i'll try do this!

**Comment by pofider** [comment]
I was testing jsreport,Embedded@1.0 in IIS with multiple applications and multiple worker processes. I found now issues so I guess this is fixed now.

Feel free to reopen if not.
