### ISSUE TITLE
waitForJs

### ISSUE THREAD

**Issue by Ackhuman** [jsreport/net#14]
Perhaps we are using it incorrectly, but we have been trying to use waitForJs (or printDelay) to prevent a race condition that is happening when using Highcharts.  I added this property to the phantom object in the server configuration, set to true, and did not add the corresponding script change to our report.  I restarted the service to pick up the configuration change and tried to run a report.  Contrary to my expectations, the report was generated almost immediately.

If this is supposed to go in the report render request, it doesn't appear to be exposed by the .NET client library.  What are we missing?

**Comment by pofider** [comment]
Yes, these are the local template options. You can specify it in the render request like this:
```cs
   var res = ReportingService.RenderAsync(new RenderRequest()
                {
                    template = new Template()
                        {
                            content = "foo",
                            recipe = "phantom-pdf",
                            engine = "jsrender",
                            additional = new
                                {
                                    phantom = new
                                        {
                                            printDelay = 1000
                                        }
                                }
                        },

                }).Result;
```

**Comment by Ackhuman** [comment]
That worked perfectly, thanks.
