### ISSUE TITLE
Not support .NET Core

### ISSUE THREAD

**Issue by ceciliaf** [jsreport/net#18]
I'm working on a project with Web Application ( .NET Core) RC2 and I see no support. This is correct?

**Comment by pofider** [comment]
Yes it is correct. It is not supported.

I could be able to port the jsreport.Client, but I'm afraid jsreport.Embedded uses too many APIs which are not ported in .net core.

**Comment by saad749** [comment]
Are there any plans to port jsreport.Client and jsReport.MVC to ASP.Net Core soon?

**Comment by pofider** [comment]
Not immediate.

We are currently trying to compile whole jsreport into single executable file and afterwards I would like to look back on .net and integrate it into it and make it working with .net core. But we are not quite there yet....

**Comment by bjrmatos** [comment]
@ScarlettCode yes, @pofider is working hard to make this a reality, AFAIK the development is in the final phase (mostly writing docs, etc) so expect to get some news really soon.

**Comment by pofider** [comment]
I've now released the preview for .NET core support to nugget. Here you can find some early information. The further information and blog posts announcing it will come. Don't forget to check "include prerelease" in VS.

https://github.com/jsreport/jsreport-dotnet
https://jsreport.net/learn/dotnet-v2

It would be great if anyone can give me some feedback.

**Comment by pofider** [comment]
The stable release for jsreport sdk v2 with .net core support is now live. This repository has been also split into multiple dedicated repositories for better maintenance and versioning. See more here

https://github.com/jsreport/jsreport-dotnet
https://jsreport.net/learn/dotnet
