### ISSUE TITLE
MVC Examples referencing Nuget packages not available

### ISSUE THREAD

**Issue by saad749** [jsreport/net#21]
The Mvc examples solution is referencing jsreport nuget packages that are not available on nuget.

This is the listing from the [github repository](https://github.com/jsreport/net/blob/master/examples/Mvc/Mvc/packages.config):

```
<package id="jsreport.Client" version="1.1.2" targetFramework="net45" />
<package id="jsreport.Embedded" version="1.0.80" targetFramework="net45" />
<package id="jsreport.MVC" version="1.1.2" targetFramework="net45" />

```

The latest packages I can find on nuget are: 
```
<package id="jsreport.Client" version="1.0.3" targetFramework="net45" />
<package id="jsreport.Embedded" version="1.0.3" targetFramework="net45" />
<package id="jsreport.MVC" version="1.0.0" targetFramework="net45" />
```

With the available packages, I get the error of "EnablejsReport could not be found".

@pofider

**Comment by saad749** [comment]
Updated with code tags

**Comment by saad749** [comment]
The last error is resolved after uninstalling the jsreport packages completely and installing them again.

**Comment by pofider** [comment]
I've fixed the version numbers in the example. Thanks.
