### ISSUE TITLE
Security Issue: Current version on Nuget (1.0.3) disables all SSL Certificate checks for entire app domain

### ISSUE THREAD

**Issue by tystol** [jsreport/net#26]
Hi guys,

I just stepped into your .net client library during debugging an unrelated issue, and by chance noticed this line:
https://github.com/jsreport/net/blob/f8a9cd62a9960bcd64288940b47b87f423743eef/jsreport/jsreport.Client/ReportingService.cs#L53

Are you aware this disables all outgoing SSL connection's server certificate validation? For the entire app, not just your library! 

We were using this version in production, and our app integrates with many other APIs over HTTPS. Quite scary that we would have been getting no cert validation for all this time.

Anyway, I can see your latest code no longer uses this, but the official version on nuget is still 1.0.3 with this security hole in it. I really think you should remove it from nuget, or ideally push up a 1.0.4 fix (assuming the 2.0 beta release is not ready yet).

**Comment by pofider** [comment]
Ah ok, very true. My fault. It was there added just for some local testing and wasn't removed.
The release 2 will come today, but I will also publish 1.0.4 to fix this.

**Comment by pofider** [comment]
This is now fixed in patch [1.0.4](https://www.nuget.org/packages/jsreport.Client/1.0.4).

I apologize for the risk it caused.

**Comment by tystol** [comment]
All good, thank's for the quick turn around. And thanks for a very interesting project you have going here!
