### ISSUE TITLE
jsreport.zip file not found. 

### ISSUE THREAD

**Issue by gutowskiap** [jsreport/net#27]
Hi
I downloaded mvc example, ran install.cmd successfully, but when I start the application I get:

System.InvalidOperationException: C:\Mvc\Mvc\bin\jsreport\jsreport.zip file not found.

at 

`EmbeddedReportingServer.StartAsync().Wait();`

**Comment by pofider** [comment]
This example is a bit outdated, could you try this one?
https://github.com/jsreport/jsreport-dotnet-aspnetcore

The jsreport .net sdk v2 works a bit differently, we are working on better docs but so far you can read about it here
https://jsreport.net/learn/dotnet

**Comment by pofider** [comment]
we've released new sdk v2 and deprecating this repository in its favor. More info here

https://github.com/jsreport/jsreport-dotnet
https://jsreport.net/learn/dotnet

In particular v2 includes jsreport.Embedded successor with much streamlined installation. More info here https://jsreport.net/learn/dotnet-local
