### ISSUE TITLE
.Net 4.0 Support

### ISSUE THREAD

**Issue by markuznw** [jsreport/net#4]
Hello, can't seem to be able to install jsreport embedded on a .net 4 project, is there compatibility only with 4.5? Because my target machine for the program is still running Windows XP.

Thanks in advance <3

**Comment by pofider** [comment]
Closing. We won't support this, unfortunately. 

If you need to call jsreport server from the .net 4. you can simply write your own  http request. The example is here https://gist.github.com/pofider/1897f8a1b6dab72a49b0
