### ISSUE TITLE
Run two embedded servers in parallel - same server

### ISSUE THREAD

**Issue by walter-psjr** [jsreport/net#6]
I am using the embedded version of jsreport on a project that is hosted on a server with balancing. We have two IIS instances being controlled by a nginx server. I tried to configure each instance to start the jsreport on different ports, for example, one in door 2000 and the other in 3000, but what starts finally ends the first.

If I boot the door in 2000 it works to the door 3000 starts. I wonder if there is the possibility of using two servers in parallel, or if you can add this feature.

**Comment by pofider** [comment]
It is true that starting EmbeddedReportingServer kills all currently running orphans no matter what ports they are running. This means you cannot start two EmbeddedReportingServer from the same application.

However it should work when starting them from different applications or just different directory. This should be enough. Is your second application running from the different path? It works for me If I run embedded server twice from the different directory.

Here is the code killing orphans:
https://github.com/jsreport/net/blob/master/jsreport/jsreport.Embedded/EmbeddedReportingServer.cs#L140

**Comment by walter-psjr** [comment]
When I published on the production server worked like you said, but in development by Visual Studio, no.

We have two projects using jsreport embedded, but we need to run both simultaneously developing because at times a project query data from another via REST.

Is there something, some configuration to solve?

Thanks

**Comment by walter-psjr** [comment]
Now is working, I believe it is something to do with the report preview run inside Visual Studio. Without the preview is working properly.

Thanks
